app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Rutas de la aplicacion
|--------------------------------------------------------------------------
| Aqui es donde se pueden registrar todas las rutas de la aplicacion
| Simplemente dile a Laravel las URIs a los cuales deberia responder
| y darle al controlador para llamar cuando una URI es solicitada
| 
|
*/
/*
	GET,POST,PUT,DELETE,RESOURCE
*/	

Route::get('/', function () {
    return view('welcome');
    //auth.login
});
//Route::group(['prefix' => 'admin','middleware' => 'auth'],function(){

Route::group(['prefix' => 'admin'],function(){

	//Route::group(['middleware' => 'admin1'], function(){

		/*Route::resource('users','UsersController');
		Route::get('users/{id}/destroy', [
		'uses'	=>	'UsersController@destroy',
		'as'	=>	'admin.users.destroy'
		
		]);*/
	//});
	Route::resource('users','UsersController');
	
	Route::get('users/{id}/destroy', ['uses'	=>	'UsersController@destroy','as'	=>	'admin.users.destroy']);
	
	/*Route::resource('personas', 'PersonasController');
	Route::get('personas/{id}/destroy',['uses' => 'PersonasController@destroy','as' => 'admin.personas.destroy']);*/

	// Asignar personas a las denuncias
	Route::resource('user_denuncia','AsignacionesController');

	//Rutas de denuncia
	Route::resource('denuncias', 'DenunciasController');
	
	Route::get('denuncias/{id}/editEstadoDenuncia',['uses' => 'DenunciasController@editEstadoDenuncia','as' => 'admin.denuncias.editEstadoDenuncia']);

	Route::put('denuncias/{id}/updateEstadoDenuncia',['uses' => 'DenunciasController@updateEstadoDenuncia','as' => 'admin.denuncias.updateEstadoDenuncia']);

	Route::get('denuncias/{id}/destroy',['uses' => 'DenunciasController@destroy','as' => 'admin.denuncias.destroy']);


	Route::resource('archivos_denuncias', 'ArchivosDenunciasController');



	//Route::get('denuncias/mostrarDato',['uses' => 'DenunciasController@mostrarDato','as' => 'admin.denuncias.mostrarDato']);

	//Ruta estados
	Route::resource('estados', 'EstadosController');
	Route::get('estados/{id}/destroy',['uses' => 'EstadosController@destroy','as' => 'admin.estados.destroy']);

	Route::resource('tipos_denuncias', 'TipoDenunciaController');
	Route::get('tipos_denuncias/{id}/destroy',['uses' => 'TipoDenunciaController@destroy','as' =>
	'admin.tipos_denuncias.destroy']);

	Route::resource('roles', 'RolesController');
	Route::get('roles/{id}/destroy',['uses' => 'RolesController@destroy','as' =>
	'admin.roles.destroy']);

});

/*Route::get('auth/login', [
	'uses'	=>	'Auth\AuthController@getLogin',
	'as' => 'auth.login'

]);
Route::get('auth/login', [
	'uses'	=>	'Auth\AuthController@postLogin',
	'as' => 'auth.login'

]);*/

Route::get('auth/logout', [
	'uses'	=>	'Auth\AuthController@getLogout',
	'as' => 'auth.logout'

]);


//--------------------------------------------------
Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('/home/f', 'DenunciasController@mostrarDato')->name('denuncia.mostrarDato');



Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::get('/admin', 'HomeController@index');
 
});

app/Estado.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Estado extends Model
{
    protected $table = "estados";

    protected $fillable = ['tipo_estado'];

    public function denuncias(){

    	return $this->hasMany('App\Denuncia');

    }
}

app/Http/Controllers/EstadosController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Estado;
use App\Http\Requests\EstadoRequest;

class EstadosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $estados = Estado::orderBy('id','ASC')->paginate(5);
        return view('admin.estados.index')->with('estados',$estados);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //dd('aprendi o no?');
        return view('admin.estados.createEstado');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EstadoRequest $request)
    {
        //dd($request->all());
        $estados = new Estado($request->all());
        $estados->save();

        return redirect()->route('admin.estados.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $estado = Estado::find($id);

        return view('admin.estados.editEstado')->with('estado',$estado);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(EstadoRequest $request, $id)
    {
        $estado = Estado::find($id);
        $estado->tipo_estado = $request->tipo_estado;

        $estado->save();

        return redirect()->route('admin.estados.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $estados = Estado::find($id);
        $estados->delete();

        return redirect()->route('admin.estados.index');
    }
}

resources/views/admin/estados/createEstado.blade.php
<!DOCTYPE html>
@section('htmlheader_title')
	Crear estados
@endsection

<html lang="en">

<link href="{{ asset('/css/skins/skin-purple.css') }}" rel="stylesheet" type="text/css" />

<script src="{{ asset('plugins/chosen/chosen.jquery.js') }}"></script>
<title> SDD - @yield('htmlheader_title', 'Crear Estado') </title>
@section('htmlheader')
    @include('layouts.partials.htmlheader')
@show

<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-purple" sidebar-collapse>
<div class="wrapper">

    @include('layouts.partials.mainheader')

    @include('layouts.partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('layouts.partials.contentheader')
        <!-- busca errores-->
        	@if(count($errors) > 0)
        		<div class="alert alert-danger" role="alert">
        			<ul>
        			@foreach($errors->all() as $error)
        				<li>{{ $error }}</li>
        			@endforeach
        			</ul>
        		</div>	
			@endif
		<!-- hasta aca -->
        <!-- Main content -->
        <section class="input-group-addon col-sm-16">
            {!! Form::open(['route' => 'admin.estados.store', 'method' => 'POST']) !!}
				

				<div class="form-group col-sm-4 ">
					{!! Form::label('tipo_estado', 'Eliga el tipo de estado') !!}

					{!! Form::select('tipo_estado',['solicitado' => 'Solicitado','aceptado' => 'Aceptado','rechazado' => 'Rechazado','proceso' => 'Proceso','baja' => 'Baja'],null,['class' =>'form-control']) !!}
				</div>
				
				
                <br>

				<div class="form-group col-xs-push--4 col-sm-3">
                    <div class="form-group" >
                    {!! Form::submit('Guardar',['class' => 'btn btn-primary']) !!}
                    
                    <a href="{{ route('admin.estados.index') }}"class="btn btn-danger" > Cancelar</a>
				</div>

			{!! Form::close() !!}
			
            @yield('main-content')

        </section><!-- /.content -->
        @section('js')
	        <!--<script>
	        	$('.select-vehiculo').chosen({})
	        	$('.select-vehiculo').chosen();
	        	$('.textarea-content').trumbowyg();
	        </script>-->


        @endsection
    </div><!-- /.content-wrapper -->

    @include('layouts.partials.controlsidebar')

    @include('layouts.partials.footer')

</div><!-- ./wrapper -->

@section('scripts')
    @include('layouts.partials.scripts')
@show

</body>
</html>

resources/views/admin/estados/editEstado.blade.php
<!DOCTYPE html>
@section('htmlheader_title')
    Editar Estado Denuncia
@endsection

<html lang="en">

<link href="{{ asset('/css/skins/skin-blue.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('/css/skins/skin-purple.css') }}" rel="stylesheet" type="text/css" />
@section('htmlheader')
    @include('layouts.partials.htmlheader')
@show

<!--

|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-purple" sidebar-collapse>
<div class="wrapper">

    @include('layouts.partials.mainheader')

    @include('layouts.partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('layouts.partials.contentheader')

        <!-- Main content -->
        <section class="input-group-addon">

            <!-- busca errores-->
            @if(count($errors) > 0)
                <div class="alert alert-danger" role="alert">
                    <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                    </ul>
                </div>  
            @endif
            
            {!! Form::open(['route' => ['admin.estados.update',$estado], 'method' => 'PUT']) !!}

                <div class="input-group col-xs-push-4">
                    {!! Form::label('tipo_estado', 'Eliga el tipo de estado') !!}

                    {!! Form::select('tipo_estado',['solicitado' => 'Solicitado','aceptado' => 'Aceptado','rechazado' => 'Rechazado','proceso' => 'Proceso','baja' => 'Baja'],null,['class' =>'form-control','placeholder' => 'ingrese estado','required']) !!}
                    
                    <div class="input-group col-xs-6 col-sm-11" >
                    {!! Form::submit('Guardar',['class' => 'btn btn-primary']) !!}
                    
                    <a href="{{ route('admin.estados.index') }}"class="btn btn-danger"> Cancelar</a>

                </div>

                </div>

                

                

            {!! Form::close() !!}
            @yield('main-content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @include('layouts.partials.controlsidebar')

    @include('layouts.partials.footer')

</div><!-- ./wrapper -->

@section('scripts')
    @include('layouts.partials.scripts')
@show

</body>
</html>

resources/views/admin/estados/index.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<link href="{{ asset('/css/skins/skin-blue.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('/css/skins/skin-purple.css') }}" rel="stylesheet" type="text/css" />

<title> SDD - @yield('htmlheader_title', 'Estados') </title>
@section('htmlheader')
    @include('layouts.partials.htmlheader')
@show

<!--

|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-purple" sidebar-collapse>
<div class="wrapper">

    @include('layouts.partials.mainheader')

    @include('layouts.partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('layouts.partials.contentheader')

        <!-- Main content -->
        <section class="content col col-lg-8">
            
            <ul class="nav navbar-nav">
            <li><a href="{{ route('admin.estados.create') }}"class="btn btn-info " >Ingresar estado </a> <hr></li>
            </ul>


        	<table class="table table-striped ">
				<thead>
					<th></th>
					<th>ID</th>
					<td></td>
					<th></th>
					<th>Tipos de estado</th>
					<th></th>
					<th></th>
					<td></td>
					<th>Editar / Eliminar</th>
				</thead> 
				<tbody>
					@foreach($estados as $estado)
						<tr>
							<th></th>
							<th>{{ $estado->id }}</th>
							<td></td>
							<td></td>
							<td>{{ $estado->tipo_estado }}</td>	
							<th></th>
							<th></th>
							<th></th>

							<td><a href="{{ route('admin.estados.edit', $estado->id) }}" class="btn btn-warning"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a>

							<a href="{{ route('admin.estados.destroy', $estado->id) }}" onclick="return confirm('¿Seguro que deseas eliminarlo?')" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span><a/></td>					
							
						</tr>		
					@endforeach
				</tbody>
			</table>
			<div class="text-center">
				{!! $estados->render() !!}
			</div>	
            @yield('main-content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @include('layouts.partials.controlsidebar')

    @include('layouts.partials.footer')

</div><!-- ./wrapper -->

@section('scripts')
    @include('layouts.partials.scripts')
@show

</body>
</html>