app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Rutas de la aplicacion
|--------------------------------------------------------------------------
| Aqui es donde se pueden registrar todas las rutas de la aplicacion
| Simplemente dile a Laravel las URIs a los cuales deberia responder
| y darle al controlador para llamar cuando una URI es solicitada
| 
|
*/
/*
	GET,POST,PUT,DELETE,RESOURCE
*/	

Route::get('/', function () {
    return view('welcome');
    //auth.login
});
//Route::group(['prefix' => 'admin','middleware' => 'auth'],function(){

Route::group(['prefix' => 'admin'],function(){

	//Route::group(['middleware' => 'admin1'], function(){

		/*Route::resource('users','UsersController');
		Route::get('users/{id}/destroy', [
		'uses'	=>	'UsersController@destroy',
		'as'	=>	'admin.users.destroy'
		
		]);*/
	//});
	Route::resource('users','UsersController');
	
	Route::get('users/{id}/destroy', ['uses'	=>	'UsersController@destroy','as'	=>	'admin.users.destroy']);
	
	/*Route::resource('personas', 'PersonasController');
	Route::get('personas/{id}/destroy',['uses' => 'PersonasController@destroy','as' => 'admin.personas.destroy']);*/

	// Asignar personas a las denuncias
	Route::resource('user_denuncia','AsignacionesController');

	//Rutas de denuncia
	Route::resource('denuncias', 'DenunciasController');
	
	Route::get('denuncias/{id}/editEstadoDenuncia',['uses' => 'DenunciasController@editEstadoDenuncia','as' => 'admin.denuncias.editEstadoDenuncia']);

	Route::put('denuncias/{id}/updateEstadoDenuncia',['uses' => 'DenunciasController@updateEstadoDenuncia','as' => 'admin.denuncias.updateEstadoDenuncia']);

	Route::get('denuncias/{id}/destroy',['uses' => 'DenunciasController@destroy','as' => 'admin.denuncias.destroy']);


	Route::resource('archivos_denuncias', 'ArchivosDenunciasController');



	//Route::get('denuncias/mostrarDato',['uses' => 'DenunciasController@mostrarDato','as' => 'admin.denuncias.mostrarDato']);

	//Ruta estados
	Route::resource('estados', 'EstadosController');
	Route::get('estados/{id}/destroy',['uses' => 'EstadosController@destroy','as' => 'admin.estados.destroy']);

	Route::resource('tipos_denuncias', 'TipoDenunciaController');
	Route::get('tipos_denuncias/{id}/destroy',['uses' => 'TipoDenunciaController@destroy','as' =>
	'admin.tipos_denuncias.destroy']);

	Route::resource('roles', 'RolesController');
	Route::get('roles/{id}/destroy',['uses' => 'RolesController@destroy','as' =>
	'admin.roles.destroy']);

});

/*Route::get('auth/login', [
	'uses'	=>	'Auth\AuthController@getLogin',
	'as' => 'auth.login'

]);
Route::get('auth/login', [
	'uses'	=>	'Auth\AuthController@postLogin',
	'as' => 'auth.login'

]);*/

Route::get('auth/logout', [
	'uses'	=>	'Auth\AuthController@getLogout',
	'as' => 'auth.logout'

]);


//--------------------------------------------------
Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('/home/f', 'DenunciasController@mostrarDato')->name('denuncia.mostrarDato');



Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::get('/admin', 'HomeController@index');
 
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    
    protected $table = "users";
    protected $fillable = ['rut','name','apellido', 'email', 'telefono','password'];

    
    protected $hidden = ['password', 'remember_token',];

    /*public function admin1(){

        return $this->tipo_usuario === 'admin1';

    }*/

    public function roles(){

        return $this->belongsToMany('App\Rol')->withTimestamps();
    }

     //es denuncias , yo lo cambie por denuncia
    public function denuncia(){
        return $this->hasMany('App\Denuncia');
    }
    

    public function denuncias(){

        return $this->belongsToMany('App\Denuncia');
    } 
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests;
use App\User;
use App\Rol;
use App\AsignarRol;
use Laracasts\Flash\Flash;
//use App\Http\Requests\UserRequest;

use Freshwork\ChileanBundle\Rut;
use ValidateRequests;
//use Validator;
//use Malahierba\ChileRut\ChileRut;

class UsersController extends Controller 
{
    

    public function index()
    {
    	$users = User::orderBy('id','ASC')->paginate(10);
        
        //$pastel = Pastel::sabor('chocolate')->first();
        //$users = User::select('189957726')->first();
        $users->each(function($users){
            
            $users->user_rol;
            
        });

        
            return view('admin.users.index')->with('users', $users);
        
        

            
        

        //dd("usuarioo");
    }

    public function create()
    {
        $users = User::orderBy('name','ASC')->lists('name','name');
    	return view('admin.users.createUser');
    }

    /*protected function validator(array $data)
    {
        return Validator::make($data, [
            'rut' => 'required|min:6|max:12|unique:users',
            'name' => 'required|max:15',
            'apellido' => 'required|min:2',
            'email' => 'required|email|max:255|unique:users',
            'telefono' => 'required|min:6',
            'password' => 'required|confirmed|min:6',
        ]);
    }*/

    public function store(Request $request)
    {
        //dd($request->all());
        $this->validate($request,[
            'rut' => 'required|cl_rut',
            'name' => 'required|max:255',
            'apellido' => 'required|min:2',
            'email' => 'required|email|max:255|unique:users',
            'telefono' => 'required|min:6|max:15|',
            'password' => 'required|confirmed|min:6'
        ]);
        //-------metodo 1 de actualizado----
        /*$user = User::find($id);
        $user->fill($request->all());
        $user->save();
        return redirect()->route('admin.users.index');*/
        //-------metodo 1 de guardado-----
    	$user = new User($request->all());
        $user->password = bcrypt($request->password);
        $user->save();
        //-------metodo 2 de guardado------
        /*$user = User::find($id);
        $user->name = $request->name;
        $user->apellido = $request->apellido;
        $user->email = $request->email;
        $user->telefono = $request->telefono;
        //$user->tipo_usuario = $request->tipo_usuario;
        $user->save();*/
        //Flash::success("se ha registrado" . $user->name . "de forma exitosa!");
        return redirect()->route('admin.users.index');
    }

    public function show($id)
    {
    	//
    }

    public function edit($id)
    {
    	$user = User::find($id);
        return view('admin.users.editUser')->with('user', $user);

    }

    public function update(Request $request, $id)
    {
    	//dd($id);
        //-------metodo 1 de guardado----
        /*$user = User::find($id);
        $user->fill($request->all());
        $user->save();
        return redirect()->route('admin.users.index');*/

        //-------metodo 2 de guardado----
        $user = User::find($id);
        $user->name = $request->name;
        $user->apellido = $request->apellido;
        $user->email = $request->email;
        $user->telefono = $request->telefono;
        //$user->tipo_usuario = $request->tipo_usuario;
        $user->save();
        Flash::success("se ha registrado" . $user->name . "de forma exitosa!");
        return redirect()->route('admin.users.index');

    }

    public function destroy($id)
    {
    	$user = User::find($id);
        $user->delete();
        //Flash::warning('El usuario'. $user->name . 'ha sido borrado de forma exitosa!');
        return redirect()->route('admin.users.index');
    }


}

resources/views/admin/users/createUser.blade.php
<!DOCTYPE html>
@section('htmlheader_title')
	Crear Usuario
@endsection

<html lang="en">

<link href="{{ asset('/css/skins/skin-purple.css') }}" rel="stylesheet" type="text/css" />

<script src="{{ asset('plugins/chosen/chosen.jquery.js') }}"></script>
@section('htmlheader')
    @include('layouts.partials.htmlheader')
    
@show

<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-purple" sidebar-collapse>
<div class="wrapper">

    @include('layouts.partials.mainheader')

    @include('layouts.partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('layouts.partials.contentheader')
        <!-- busca errores-->
        	@if(count($errors) > 0)
        		<div class="alert alert-danger" role="alert">
        			<ul>
        			@foreach($errors->all() as $error)
        				<li>{{ $error }}</li>
        			@endforeach
        			</ul>
        		</div>	
			@endif
		<!-- hasta aca -->
        <!-- Main content -->
        <div class="panel panel-info class ">
                
                <div class="panel-heading">Instrucciones </div>
                <div class="panel-body">
                • Complete los campos dados y luego presione el boton "Registrar"
                <div></div>
                • Si desea volver a la pagina anterior, presione "Cancelar" 
                </div>
            </div>
        <section class="input-group-addon">


        	<p class="login-box-msg">{{ trans('Registre un nuevo usuario') }}</p>
            {!! Form::open(['route' => 'admin.users.store', 'method' => 'POST']) !!}

                <div class="form-group  col-xs-push-2 col-sm-7">
                    
    				<div class="form-group has-feedback">
<<<<<<< HEAD
                        <input type="cl_rut" class="form-control" placeholder="{{ trans('rut') }}" name="rut" onchange="" value="{{ old('rut') }}"/>
=======
                        <input type="cl_rut" class="form-control" placeholder="{{ trans('rut') }}" name="rut" value="{{ old('rut') }}"/>
>>>>>>> 48d0ade3a5cfeb281867d15ab2cfef86afc2828a
                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    </div>

                    <div class="form-group has-feedback">
                        <input type="name" class="form-control"  placeholder="{{ trans('nombres') }}" name="name" value="{{ old('name') }}"/>
                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    </div>

                    <!--div class="input-group">
                        <input type="text" class="form-control" aria-label="...">
                        <div class="input-group-btn">
                                
                        </div>
                    </div-->

                    <div class="form-group has-feedback" >
                        <input type="apellido" class="form-control" placeholder="{{ trans('apellidos') }}" name="apellido" value="{{ old('apellido') }}"/>
                        <span class="glyphicon glyphicon-user form-control-feedback"></span>
                    </div>
                    
                    <div class="form-group has-feedback">
                        <input type="email" class="form-control" placeholder="{{ trans('email') }}" name="email" value="{{ old('email') }}"/>
                        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
                    </div>

                    <div class="form-group has-feedback">
                        <input type="telefono" class="form-control" placeholder="{{ trans('telefono') }}" name="telefono" value="{{ old('telefono') }}"/>
                        <span class="glyphicon glyphicon-earphone form-control-feedback"></span>
                    </div>
                    
                    <div class="form-group has-feedback">
                        <input type="password" class="form-control" placeholder="{{ trans('Contraseña') }}" name="password"/>
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    </div>
                    
                    <div class="form-group has-feedback">
                        <input type="password" class="form-control" placeholder="{{ trans('Reescribir contraseña') }}" name="password_confirmation"/>
                        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                    </div>

                    <!--accion del tipo de usuario -->
                    <!--<div class="form-group has-feedback">

                        {!! Form::label('tipo_usuario','tipo') !!}
                        {!! Form::select('tipo_usuario',[''=> 'seleccione un nivel..','admin2' => 'Administrador 2','admin1' => 'Administrador 1'],null) !!}
                        
                    </div>-->
                    
                    <div class="form-group">
                        {!! Form::submit('Registrar',['class' => 'btn btn-primary']) !!}

                        <a href="{{ route('admin.users.index') }}"class="btn btn-danger mb-3"> Cancelar</a>
                    </div>
                </div>
			{!! Form::close() !!}
			
            @yield('main-content')

        </section><!-- /.content -->
        
    </div><!-- /.content-wrapper -->

    @include('layouts.partials.controlsidebar')

    @include('layouts.partials.footer')

</div><!-- ./wrapper -->

@section('scripts')
    @include('layouts.partials.scripts')
    @section('js')
            @section('js')
            <script>
                function validaRut(Objeto) {
                    var tmpstr = "";
                    var intlargo = Objeto.value
                    if (intlargo.length > 0) {
                        crut = Objeto.value
                        largo = crut.length;
                        if (largo < 2) {
                            alert('rut inválido')
                            Objeto.focus()
                            return false;
                        }
                        for (i = 0; i < crut.length; i++)
                            if (crut.charAt(i) != ' ' && crut.charAt(i) != '.' && crut.charAt(i) != '-') {
                                tmpstr = tmpstr + crut.charAt(i);
                            }
                        rut = tmpstr;
                        crut = tmpstr;
                        largo = crut.length;
                        if (largo > 2) rut = crut.substring(0, largo - 1);
                        else rut = crut.charAt(0);
                        dv = crut.charAt(largo - 1);
                        if (rut == null || dv == null) return 0;
                        var dvr = '0';
                        suma = 0;
                        mul = 2;
                        for (i = rut.length - 1; i >= 0; i--) {
                            suma = suma + rut.charAt(i) * mul;
                            if (mul == 7) mul = 2;
                            else mul++;
                        }
                        res = suma % 11;
                        if (res == 1) dvr = 'k';
                        else if (res == 0) dvr = '0';
                        else {
                            dvi = 11 - res;
                            dvr = dvi + "";
                        }
                        if (dvr != dv.toLowerCase()) {
                            alert('El rut ingresado es invalido');
                            // Objeto.style.backgroundColor = '#F18C8C';
                            Objeto.value = "";
                            Objeto.focus();
                            return false;
                        }
                        //Objeto.style.backgroundColor = '#6FD84C';
                        Objeto.focus()
                        return true;
                    }
                }
            </script>


        @endsection
@show

</body>
</html>

resources/views/admin/users/editUser.blade.php
<!DOCTYPE html>
@section('htmlheader_title')
    Editar usuario
@endsection

<html lang="en">

<link href="{{ asset('/css/skins/skin-purple.css') }}" rel="stylesheet" type="text/css" />
@section('htmlheader')
    @include('layouts.partials.htmlheader')
@show

<!--

|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-purple" sidebar-collapse>
<div class="wrapper">

    @include('layouts.partials.mainheader')

    @include('layouts.partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('layouts.partials.contentheader')

        <!-- Main content -->
        <section class="content">

            <!-- busca errores-->
            @if(count($errors) > 0)
                <div class="alert alert-danger" role="alert">
                    <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                    </ul>
                </div>  
            @endif
            
            {!! Form::open(['route' => ['admin.users.update',$user], 'method' => 'PUT']) !!}

                <div class="form-group">
                    {!! Form::label('name', 'Nombre') !!}
                    {!! Form::text('name',$user->name,['class' => 'form-control','placeholder' => 'nombre usuario','required']) !!}
                </div>

                <div class="form-group">
                    {!! Form::label('apellido', 'Apellido') !!}
                    {!! Form::text('apellido',$user->apellido,['class' => 'form-control','placeholder' => 'Apellido usuario','required']) !!}
                </div>

                <!-- agregar un combo box------------------------------------------>

                <div class="form-group">
                    {!! Form::label('email', 'Email') !!}
                    {!! Form::text('email',$user->email,['class' => 'form-control','placeholder' => 'Ingrese el email','required']) !!}
                </div>

                <div class="form-group">
                    {!! Form::label('telefono', 'Telefono') !!}
                    {!! Form::text('telefono',$user->telefono,['class' => 'form-control','placeholder' => 'Telefono usuario','required']) !!}
                </div>





                <!--<div class="form-group">
                    {!! Form::label('tipo_usuario','tipo') !!}
                    {!! Form::select('tipo_usuario',['admin2' => 'Administrador 2','admin1' => 'Administrador 1'],$user->tipo_usuario,['class' =>'form-control']) !!}
                </div>-->



                <div class="form-group">
                    {!! Form::submit('Editar',['class' => 'btn btn-primary']) !!}
                </div>

            {!! Form::close() !!}
            @yield('main-content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @include('layouts.partials.controlsidebar')

    @include('layouts.partials.footer')

</div><!-- ./wrapper -->

@section('scripts')
    @include('layouts.partials.scripts')
@show

</body>
</html>

resources/views/admin/users/index.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<link href="{{ asset('/css/skins/skin-purple.css') }}" rel="stylesheet" type="text/css" />
<title> SDD - @yield('htmlheader_title', 'Usuarios') </title>
@section('htmlheader')
    @include('layouts.partials.htmlheader')
@show

<!--

|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-purple" sidebar-collapse>
<div class="wrapper">

    @include('layouts.partials.mainheader')

    @include('layouts.partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('layouts.partials.contentheader')

        <!-- Main content -->
        <section class="content">
        	
        	<div class="panel panel-info class ">
        		
  				<div class="panel-heading">Instrucciones </div>
  			 	<div class="panel-body">• </div>
  			</div>
  			 	@if( $users->count() < 1 )
				    <div class="panel panel-danger ">
        		
  						<div class="panel-heading">Atencion! </div>
  			 			<div class="panel-body">• No hay usuarios 	</div>
  			 		</div>
				@endif
        	<ul class="nav navbar-nav">
            <li><a href="{{ route('admin.users.create') }}"class="btn btn-info">Ingresar Usuario</a><hr></li>
            </ul>
            
        	<table id="users"  class="table table-striped">
				<thead>
					<th>ID</th>
					<th>Rut</th>
					<th>Rol</th>
					<th>Nombre</th>
					<th>Apellido</th>
					<th>Email</th>
					<th>telefono</th>
					<th></th>
					<th>Editar / Eliminar</th>
				</thead> 
				<tbody>
					
					
					@foreach($users as $user)
					
						<tr>
							<td>{{ $user->id }}</td>
							<td>{{ $user->rut }}</td>
			
							<td></td>
							
							<td>{{ $user->name }}</td>
							<td>{{ $user->apellido }}</td>
							<td>{{ $user->email }}</td>
							<td>{{ $user->telefono }}</td>
							
							<td>
								
									<!--<span class="label label-danger">{{ $user->tipo_usuario }}</span>
								
									<span class="label label-primary">{{ $user->tipo_usuario }}</span>-->
								
							</td>
							<td><a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-warning"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a>

							<a href="{{ route('admin.users.destroy', $user->id) }}" onclick="return confirm('¿Seguro que deseas eliminarlo?')" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span><a/></td>					
							
						</tr>		
					@endforeach
					
				</tbody>
			</table>
			<!--table class="panel panel-default">

				<thead >

					<th class="panel-body">ID</th>

					<th class="panel-body">Roles</th>
				</thead>
				<tbody>
					@foreach($users as $rol_user)
						<tr>
							<td class="panel-body"> {{ $rol_user->id }}</td>
							<td>
                                <a >
                                    {{ $rol_user->rol_id }}
                                </a>
                            </td>
						</tr>
					@endforeach
				</tbody>
			</table-->
			<div class="text-center">
				{!! $users->render() !!}
			</div>	
            @yield('main-content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @include('layouts.partials.controlsidebar')

    @include('layouts.partials.footer')

</div><!-- ./wrapper -->

@section('scripts')
    @include('layouts.partials.scripts')
@show

</body>
</html>