app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Rutas de la aplicacion
|--------------------------------------------------------------------------
| Aqui es donde se pueden registrar todas las rutas de la aplicacion
| Simplemente dile a Laravel las URIs a los cuales deberia responder
| y darle al controlador para llamar cuando una URI es solicitada
| 
|
*/
/*
	GET,POST,PUT,DELETE,RESOURCE
*/	

Route::get('/', function () {
    return view('welcome');
    //auth.login
});
//Route::group(['prefix' => 'admin','middleware' => 'auth'],function(){

Route::group(['prefix' => 'admin'],function(){

	//Route::group(['middleware' => 'admin1'], function(){

		/*Route::resource('users','UsersController');
		Route::get('users/{id}/destroy', [
		'uses'	=>	'UsersController@destroy',
		'as'	=>	'admin.users.destroy'
		
		]);*/
	//});
	Route::resource('users','UsersController');
	
	Route::get('users/{id}/destroy', ['uses'	=>	'UsersController@destroy','as'	=>	'admin.users.destroy']);
	
	/*Route::resource('personas', 'PersonasController');
	Route::get('personas/{id}/destroy',['uses' => 'PersonasController@destroy','as' => 'admin.personas.destroy']);*/

	// Asignar personas a las denuncias
	Route::resource('user_denuncia','AsignacionesController');

	//Rutas de denuncia
	Route::resource('denuncias', 'DenunciasController');
	
	Route::get('denuncias/{id}/editEstadoDenuncia',['uses' => 'DenunciasController@editEstadoDenuncia','as' => 'admin.denuncias.editEstadoDenuncia']);

	Route::put('denuncias/{id}/updateEstadoDenuncia',['uses' => 'DenunciasController@updateEstadoDenuncia','as' => 'admin.denuncias.updateEstadoDenuncia']);

	Route::get('denuncias/{id}/destroy',['uses' => 'DenunciasController@destroy','as' => 'admin.denuncias.destroy']);


	Route::resource('archivos_denuncias', 'ArchivosDenunciasController');



	//Route::get('denuncias/mostrarDato',['uses' => 'DenunciasController@mostrarDato','as' => 'admin.denuncias.mostrarDato']);

	//Ruta estados
	Route::resource('estados', 'EstadosController');
	Route::get('estados/{id}/destroy',['uses' => 'EstadosController@destroy','as' => 'admin.estados.destroy']);

	Route::resource('tipos_denuncias', 'TipoDenunciaController');
	Route::get('tipos_denuncias/{id}/destroy',['uses' => 'TipoDenunciaController@destroy','as' =>
	'admin.tipos_denuncias.destroy']);

	Route::resource('roles', 'RolesController');
	Route::get('roles/{id}/destroy',['uses' => 'RolesController@destroy','as' =>
	'admin.roles.destroy']);

});

/*Route::get('auth/login', [
	'uses'	=>	'Auth\AuthController@getLogin',
	'as' => 'auth.login'

]);
Route::get('auth/login', [
	'uses'	=>	'Auth\AuthController@postLogin',
	'as' => 'auth.login'

]);*/

Route::get('auth/logout', [
	'uses'	=>	'Auth\AuthController@getLogout',
	'as' => 'auth.logout'

]);


//--------------------------------------------------
Route::auth();

Route::get('/home', 'HomeController@index');

Route::get('/home/f', 'DenunciasController@mostrarDato')->name('denuncia.mostrarDato');



Route::group(['middleware' => 'web'], function () {
    Route::auth();
    Route::get('/admin', 'HomeController@index');
 
});

resources/views/admin/tipos_denuncias/createTipoDenuncia.blade.php
<!DOCTYPE html>
@section('htmlheader_title')
	Crear tipos denuncia
@endsection

<html lang="en">

<link href="{{ asset('/css/skins/skin-purple.css') }}" rel="stylesheet" type="text/css" />

<script src="{{ asset('plugins/chosen/chosen.jquery.js') }}"></script>
@section('htmlheader')
    @include('layouts.partials.htmlheader')
@show

<!--
BODY TAG OPTIONS:
=================
Apply one or more of the following classes to get the
desired effect
|---------------------------------------------------------|
| SKINS         | skin-blue                               |
|               | skin-black                              |
|               | skin-purple                             |
|               | skin-yellow                             |
|               | skin-red                                |
|               | skin-green                              |
|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-purple" sidebar-collapse>
<div class="wrapper">

    @include('layouts.partials.mainheader')

    @include('layouts.partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('layouts.partials.contentheader')
        <!-- busca errores-->
        	@if(count($errors) > 0)
        		<div class="alert alert-danger" role="alert">
        			<ul>
        			@foreach($errors->all() as $error)
        				<li>{{ $error }}</li>
        			@endforeach
        			</ul>
        		</div>	
			@endif
		<!-- hasta aca -->
        <!-- Main content -->
        <section class="input-group-addon">
            {!! Form::open(['route' => 'admin.tipos_denuncias.store', 'method' => 'POST']) !!}
				

				<div class="form-group col-xs-push--1 col-sm-4">

					{!! Form::label('tipo', 'Ingrese un tipo de denuncia') !!}

					{!! Form::text('tipo',null,['class' => 'form-control','placeholder' => 'Ej:Laboral','required']) !!}

                </div>   

				<div class="form-group col-xs-push--4 col-sm-3">
                    <div class="form-group" >
                    {!! Form::submit('Guardar',['class' => 'btn btn-primary']) !!}
                    
                    <a href="{{ route('admin.tipos_denuncias.index') }}"class="btn btn-danger mb-3"> Cancelar</a>
                </div>

			{!! Form::close() !!}
			
            @yield('main-content')

        </section><!-- /.content -->
        @section('js')
	        <!--<script>
	        	$('.select-vehiculo').chosen({})
	        	$('.select-vehiculo').chosen();
	        	$('.textarea-content').trumbowyg();
	        </script>-->


        @endsection
    </div><!-- /.content-wrapper -->

    @include('layouts.partials.controlsidebar')

    @include('layouts.partials.footer')

</div><!-- ./wrapper -->

@section('scripts')
    @include('layouts.partials.scripts')
@show

</body>
</html>

resources/views/admin/tipos_denuncias/editTipoDenuncia.blade.php
<!DOCTYPE html>
@section('htmlheader_title')
	Editar persona
@endsection

<!--	-->

<html lang="en">
<link href="{{ asset('/css/skins/skin-green.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('/css/skins/skin-purple.css') }}" rel="stylesheet" type="text/css" />


@section('htmlheader')
    @include('layouts.partials.htmlheader')
@show

<body class="skin-purple" sidebar-collapse>
<div class="wrapper">

    @include('layouts.partials.mainheader')

    @include('layouts.partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('layouts.partials.contentheader')

        <!-- Main content -->
        <section class="content">
        	<!-- busca errores-->
        	@if(count($errors) > 0)
        		<div class="alert alert-danger" role="alert">
        			<ul>
        			@foreach($errors->all() as $error)
        				<li>{{ $error }}</li>
        			@endforeach
        			</ul>
        		</div>	
			@endif
			<!-- hasta aca -->
			<!-- Aqui se arma el formulario -->
            {!! Form::open(['route' => ['admin.tipos_denuncias.update',$tipo_denuncia], 'method' => 'PUT']) !!}


				<div class="form-group">
					{!! Form::label('tipo', 'Tipo Denuncia') !!}
					{!! Form::text('tipo',$tipo_denuncia->tipo,['class' => 'form-control','placeholder' => 'ingrese tipo denuncia','required']) !!}
				</div>

				
				<div class="form-group">
					{!! Form::submit('Editar',['class' => 'btn btn-primary']) !!}
				</div>

			{!! Form::close() !!}
            @yield('main-content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @include('layouts.partials.controlsidebar')

    @include('layouts.partials.footer')

</div><!-- ./wrapper -->

@section('scripts')
    @include('layouts.partials.scripts')
@show

</body>

</html>

resources/views/admin/tipos_denuncias/index.blade.php
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<link href="{{ asset('/css/skins/skin-blue.css') }}" rel="stylesheet" type="text/css" />
<link href="{{ asset('/css/skins/skin-purple.css') }}" rel="stylesheet" type="text/css" />

<title> SDD - @yield('htmlheader_title', 'Tipos de denuncia') </title>
@section('htmlheader')
    @include('layouts.partials.htmlheader')
@show

<!--

|---------------------------------------------------------|
|LAYOUT OPTIONS | fixed                                   |
|               | layout-boxed                            |
|               | layout-top-nav                          |
|               | sidebar-collapse                        |
|               | sidebar-mini                            |
|---------------------------------------------------------|
-->
<body class="skin-purple" sidebar-collapse>
<div class="wrapper">

    @include('layouts.partials.mainheader')

    @include('layouts.partials.sidebar')

    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">

        @include('layouts.partials.contentheader')

        <!-- Main content -->
        <section class="content col col-lg-8">
            
            <ul class="nav navbar-nav">
            <li><a href="{{ route('admin.tipos_denuncias.create') }}"class="btn btn-info">Ingresar tipo denuncia</a><hr></li>
            </ul>

        	<table class="table table-striped">

				<thead>
					<th>ID</th>
					<th>Tipos de denuncia</th>
					
					<th></th>
					<th></th>
					<th>Editar / Eliminar</th>
				</thead> 
				<tbody>
					@foreach($tipos_denuncias as $tipo_denuncia)
						<tr>
							<th>{{ $tipo_denuncia->id }}</th>
							<td>{{ $tipo_denuncia->tipo }}</td>
							
							<td></td><td></td>
							
							<td><a href="{{ route('admin.tipos_denuncias.edit', $tipo_denuncia->id) }}" class="btn btn-warning"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></a>

							<a href="{{ route('admin.tipos_denuncias.destroy', $tipo_denuncia->id) }}" onclick="return confirm('¿Seguro que deseas eliminarlo?')" class="btn btn-danger"><span class="glyphicon glyphicon-remove-circle" aria-hidden="true"></span><a/></td>					
							
						</tr>		
					@endforeach
				</tbody>
			</table>
			<div class="text-center">
				{!! $tipos_denuncias->render() !!}
			</div>	
            @yield('main-content')
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->

    @include('layouts.partials.controlsidebar')

    @include('layouts.partials.footer')

</div><!-- ./wrapper -->

@section('scripts')
    @include('layouts.partials.scripts')
@show

</body>
</html>